version: '3.2'
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000

  prometheus:
    build: ./prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    depends_on:
      - cadvisor
  
  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    container_name: cadvisor
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
      - redis
  
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379